name: "Portfolio Generator"
author: "Victor-Jose Lande"
description: "Generates a feed for a portfolio from YAML file"
runs: 
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red"
inputs: 
  email: 
    description: The commiteræs email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}